# Generated by Django 4.0.3 on 2022-03-20 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='cinema.actor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default=datetime.date(2022, 3, 20)),
        ),
    ]
